### ISSUE TITLE
Getting wrong payload after handler

### ISSUE THREAD

**Issue by jdkanani** [1248/microcoap#32]
I am facing weird issue on ESP8266. `outpkt->payload.p` value is changing after handling request.

Handler:
```c
int handleGetDeviceInfo(coap_rw_buffer_t *scratch, const coap_packet_t *inpkt, coap_packet_t *outpkt, uint8_t high, uint8_t low) {
    const char result[] = "12";
    int r = coap_make_response(scratch, outpkt, (const uint8_t*)result, 2, high, low, &inpkt->tok, COAP_RSPCODE_CONTENT, COAP_CONTENTTYPE_TEXT_PLAIN);
    Serial.print("In handler after make response : ");
    Serial.print(outpkt->payload.p[0], DEC);
    Serial.print(outpkt->payload.p[1], DEC);
    return r;
}
```
This code prints: "In handler after make response: 4950"

`coap_handle_req` in `coap.cpp`, after match:
```c
int r= ep->handler(scratch, inpkt, outpkt, inpkt->hdr.id[0], inpkt->hdr.id[1]);
Serial.print("After handler : ");
Serial.print(outpkt->payload.p[0], DEC);
Serial.println(outpkt->payload.p[1], DEC);
return r;
```
While this code prints: "After handler :  68134"

I don't what I am missing. Any help would be appreciated. Thanks.

**Comment by pcsrule** [comment]
For future debugging I would recommend printing values of this nature in hexadecimal, as two concatenated decimal values doesn't make much sense and hex can make issues of precision/endianess/sign more visible. It's very difficult to determine what your issue is when I can't tell what was in memory to begin with. Nothing stands out as immediately wrong in the code you've posted, so I'd encourage you to try a hex printout and see if anything stands out.

**Comment by jdkanani** [comment]
So I just printed hex values and results are different in handler and after handler:

```
In handler after make response : 31 32
After handler : 44 86
```

**Edit:** @pcsrule  I just noticed your edits. "static" did the trick - pretty scary though. Thanks a lot.
